#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("msg_address0", 4, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("msg_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("msg_q0", 256, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("msg_address1", 4, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("msg_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("msg_q1", 256, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("code", 8, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("code_size", 64, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("state_address0", 14, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("state_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("state_we0", 32, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("state_d0", 256, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("state_q0", 256, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("state_address1", 14, hls_out, 3, "ap_memory", "MemPortADDR2", 1),
	Port_Property("state_ce1", 1, hls_out, 3, "ap_memory", "MemPortCE2", 1),
	Port_Property("state_we1", 32, hls_out, 3, "ap_memory", "MemPortWE2", 1),
	Port_Property("state_d1", 256, hls_out, 3, "ap_memory", "MemPortDIN2", 1),
	Port_Property("state_q1", 256, hls_in, 3, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("storage_stream_in_V_dout", 256, hls_in, 4, "ap_fifo", "fifo_data", 1),
	Port_Property("storage_stream_in_V_empty_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 1),
	Port_Property("storage_stream_in_V_read", 1, hls_out, 4, "ap_fifo", "fifo_update", 1),
	Port_Property("storage_stream_out_V_din", 256, hls_out, 5, "ap_fifo", "fifo_data", 4),
	Port_Property("storage_stream_out_V_full_n", 1, hls_in, 5, "ap_fifo", "fifo_status", 4),
	Port_Property("storage_stream_out_V_write", 1, hls_out, 5, "ap_fifo", "fifo_update", 4),
	Port_Property("result_address0", 9, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("result_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("result_we0", 20, hls_out, 6, "ap_memory", "mem_we", 1),
	Port_Property("result_d0", 160, hls_out, 6, "ap_memory", "mem_din", 1),
};
const char* HLS_Design_Meta::dut_name = "execute_contract_fpga";
